### ISSUE TITLE
Document which versions of VDAF and DAP are implemented

### ISSUE THREAD

**Issue by tgeoghegan** [divviup/divviup-ts#10]
Having merged #7, divviup-ts is now an implementation of the not-yet-released `draft-ietf-cfrg-vdaf-01`. That's a fine and sensible choice to make. However the project's documentation should be explicit about what versions of the VDAF and DAP specifications are implemented.

Specifying a version of DAP should in turn imply a version of VDAF, so arguably it's on us document editors to get our shoot together and produce a coherent set of draft versions.

**Comment by jbr** [comment]
Currently I'm not entirely sure what the answer for this is. I think it's "as close to the current versions of vdaf/prio3/dap as continues to be compatible with main of janus" — known exceptions are #17 and #16
