### ISSUE TITLE
Wire up `Prio3Aes128CountVec`

### ISSUE THREAD

**Issue by tgeoghegan** [divviup/divviup-ts#100]
Divvi Up should allow tasks to use [`prio::vdaf::prio3::Prio3Aes128CountVec`](https://docs.rs/prio/0.8.4/prio/vdaf/prio3/type.Prio3Aes128CountVec.html).

**Comment by jbr** [comment]
Is there a version of the draft spec that includes this instantiation?

**Comment by tgeoghegan** [comment]
There is not, so the only reference is the Rust implementation. For what it's worth, everyone who is experimenting with this VDAF is unblocked by `libprio-rs`, so this issue could be put on the backburner until a specification for `CountVec` is available.

**Comment by divergentdave** [comment]
We can address this as part of #359, now that the VDAF is specified.
