### ISSUE TITLE
Support ES modules for `dap` for compat with bundlers like Vite

### ISSUE THREAD

**Issue by tanyav2** [divviup/divviup-ts#1033]
The `dap` package lacks support for ES modules, making it difficult to use with module bundlers like Vite. This can be fixed by adding the `module` field to `package.json`  to specify the ES module entry point and `exports` field to define explicit import paths for both ESM and CommonJS users. Something like-
https://github.com/tinfoilanalytics/divviup-ts/commit/b457670c6866beb51a4a79e69d25fa112c1455f0

**Comment by divergentdave** [comment]
It looks like the `module` field is used by bundlers only. Just setting up the `"exports"` key might be a better way to solve this, as it looks like that's the preferred solution now.

Relevant docs:
* https://esbuild.github.io/api/#main-fields
* https://docs.npmjs.com/cli/v10/configuring-npm/package-json#main
* https://nodejs.org/api/packages.html#main
* https://nodejs.org/api/packages.html#type
* https://nodejs.org/api/packages.html#exports

**Comment by tanyav2** [comment]
Yeah that works actually. Should I make a PR?

**Comment by divergentdave** [comment]
Sure, thank you!
