### ISSUE TITLE
Typedocs are broken on main

### ISSUE THREAD

**Issue by jbr** [divviup/divviup-ts#112]

**Comment by tgeoghegan** [comment]
This was fixed insofar as the workflow now gets a green checkmark by https://github.com/divviup/divviup-ts/pull/275, but [@jbr pointed out](https://github.com/divviup/divviup-ts/pull/275#issuecomment-1531743542) that this still doesn't work right and needs more work.

**Comment by divergentdave** [comment]
Fixed in #278 and #280
