### ISSUE TITLE
Integrate interpolateRoots from upstream galois library

### ISSUE THREAD

**Issue by divergentdave** [divviup/divviup-ts#22]
Currently, wire polynomials are built using `interpolate()` from the Galois library, which appears to be using Lagrange interpolation, in $O(n^2)$ time. The x-coordinates are calculated in `genericFlp.ts` as the powers of $\alpha$, a $2^P$-th root of unity. I think we could instead use `interpolateRoots()` here, which uses FFT interpolation. The library documentation is rather brief, but judging by [its unit tests](https://github.com/GuildOfWeavers/galois/blob/1be0b6a3df802e84140808a5e02a9650b9b36b0d/tests/PrimeField.spec.ts#L1209-L1249) I think we could use `interpolateRoots()` as a drop-in replacement, since our x-coordinate array is the set of $2^P$-th roots of unity. This should be more efficient, though the absolute difference may be small since the polynomial order may be around 4 to 16 thus far.

**Comment by jbr** [comment]
Unfortunately, trying this has uncovered a bug in the library. I'll see if I can get them to merge a patch and release a new version

**Comment by jbr** [comment]
The lines in question are [here](https://github.com/GuildOfWeavers/galois/blob/master/lib/PrimeField.ts#L953-L964) — They're assuming that there are exactly four elements in `values` and `roots` but we only have two in each

**Comment by jbr** [comment]
PR here: https://github.com/GuildOfWeavers/galois/pull/28
