### ISSUE TITLE
Rename PrepareMessage to PrepareState

### ISSUE THREAD

**Issue by divergentdave** [divviup/divviup-ts#31]
Following the lead of divviup/libprio-rs#230, we should rename `PrepareMessage` to `PrepareState` for clarity. (This type is only stored locally by each aggregator, and not sent anywhere)

**Comment by BranLwyd** [comment]
nit: `PrepareStep` (rather than `PrepareMessage`) to `PrepareState`. (and agreed, this is a good idea; there are some places that already name things e.g. `prepare_state` but especially older code preferred `prepare_step`)
