### ISSUE TITLE
DAP-07/VDAF-07 compatibility

### ISSUE THREAD

**Issue by tgeoghegan** [divviup/divviup-ts#359]
The new drafts primary deal with the aggregation sub-protocol, but there are some relevant changes for the client:

- [x] Domain separation strings
- [x] `struct Report` now has exactly two encrypted input shares
- [x] SHAKE128
- [x] Prio3SumVec
- [x] Prio3Histogram

[DAP-04 to DAP-07 diff](https://author-tools.ietf.org/iddiff?url1=draft-ietf-ppm-dap-04&url2=draft-ietf-ppm-dap-07&difftype=--html)
[VDAF-05 to VDAF-07 diff](https://author-tools.ietf.org/iddiff?url1=draft-irtf-cfrg-vdaf-05&url2=draft-irtf-cfrg-vdaf-07&difftype=--html)

**Comment by divergentdave** [comment]
We'll want to hop to DAP-06/VDAF-07 next, which will include replacing cSHAKE128 with SHAKE128, the new Prio3SumVec, and circuit changes to Prio3Histogram.
