### ISSUE TITLE
Rationalize `module` and `moduleResolution` compiler options

### ISSUE THREAD

**Issue by divergentdave** [divviup/divviup-ts#405]
We currently set `"module": "esnext"` and `"moduleResolution": "node"` (which is an alias for "node10"). While this works for now, it is somewhat incoherent, as it is targeting the module resolution algorithm of versions of node that did not fully support ESM, meanwhile our `package.json` includes `"type": "module"`. This combination is at risk of being unsupported in future versions of TypeScript, since it doesn't represent any real JS runtime.

According to a [WIP version of module documentation](https://gist.github.com/andrewbranch/79f872a8b9f0507c9c5f2641cfb3efa6), the recommended choice of options for libraries is `"module": "nodenext", "moduleResolution": "nodenext"`, because these are the strictest choices, and would provide the broadest compatibility with different app-level compiler options.

We cannot immediately use these options because of similar incompatibility issues with our dependencies. (at least, without some unsettling workarounds) I have filed a one-line PR against `one-webcrypto` to fix an [issue with their exports in recent versions of TS](https://arethetypeswrong.github.io/?p=one-webcrypto%401.0.3). There are broader [issues with jsSHA](https://arethetypeswrong.github.io/?p=jssha%403.3.1), because of the effects of their packaging tooling. This causes discrepancies between TypeScript's model of how default exports and module namespaces are handled in CJS<->ESM interop scenarios versus how Node.js actually imports modules, how bundlers transform files, etc. (There are a lot of moving parts in the build pipeline, including rollup, tsc, terser, and a TypeScript-specific rollup plugin, and I'm not sure what the root cause is yet)

For the time being, our code runs okay in Node.js, and we have one report of a user successfully bundling our library for use in a web browser, so this isn't pressing. If these two upstream libraries get patched to work with `nodenext`, then we should build and test with those options.

**Comment by jbr** [comment]
Relatedly, I wonder if we should offer a swc/esbuild bundled build or stick with our current "simplest possible, tsc-only" build
